### ISSUE TITLE
orcidId vs. researcherId

### ISSUE THREAD

**Issue by mjaved495** [openrif/vivo-isf-ontology#658]
I am wondering why orcidId is defined as an ObjectProperty and  researcherId is defined as a Data type Property. 
Should both not be defined as data type properties ?

https://jira.duraspace.org/browse/VIVO-1371

**Comment by mconlon17** [comment]
Good question.  I think there is some confusion regarding ORCiD in VIVO.  Individuals asserted to be an Owl:Thing, but clearly need some other kind of type assertions to clarify what kind of things they are.  The orcid thing can then have properties such as the orcid value, and the assertion "confirmedOrcidId"

Orcid was implemented this way to support VIVO functionality allowing real-time interaction with ORCiD via their API to confirm the ORCiD.

    <personURI> vivo:orcidId <orcidURI> .
    <orcidURI> a owl:Thing .
    <orcidURI> vivo:confirmedOrcidId <personURI> .

Would this lead us to suggest that all identifiers be objects so that they can support properties of their own? That ORCiD be refactored to avoid this construct?  Or that we add a type to discern ORCiD things.

**Comment by mconlon17** [comment]
Seems important to have ORCiD URI asserted to be such.  Currently VIVO allows ORCiD URI to be the subjects and objects of triples without the ability to discern what type of thing the URI is, other than an owl:Thing.  I believe we should have

    <orcidURI> a vivo:OrcidId .

which would then be inferred to be an owl:Thing.

**Comment by mjaved495** [comment]
I asked this question long ago and now I think it is correct to have ORCID as URI and researchId as string. 

The ORCID iD is an https URI with a 16-digit number that is compatible .....
https://support.orcid.org/knowledgebase/articles/116780-structure-of-the-orcid-identifier

**Comment by mjaved495** [comment]
we should close this issue. May I ?

**Comment by mconlon17** [comment]
Yes.  My comment is about another issue which needs to be opened.  Please close this one and I will open one on the new topic.
